LOG_FILE = './log/file.log'
RAW_FOLDER = './data/raw/'
INTERIM_FOLDER = './data/interim/'
PROCESSED_FOLDER = './data/processed/'
MODELS_FOLDER = './models/'
REPORTS_FOLDER = './reports/'
RANDOM_STATE = 42
X_TRAIN = 'X_train_4th_dataprep.pqt'
X_TEST = 'X_test_4th_dataprep.pqt'
Y_TRAIN = 'y_train_4th_dataprep.pqt'
T_TEST = 'y_test_4th_dataprep.pqt'
MODEL = 'model_10th_experiment.sav'
DATA_PREP = 'dataprep_pipeline_4th_experiment.sav'
