name: Makefile CI

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9.7'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

    - name: Install dependencies
      run: make install

    - name: lint
      run: make lint

    - name: Run check
      run: make test
