name: Makefile CI

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.7"]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: lint
      run: make lint

    - name: Run check
      run: make test
